#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SKIP_GIT=0
SKIP_DESKTOP=0
SKIP_PACKAGE_INSTALL=0
SKIP_RUNTIME_IMAGE=0
RUN_COMPOSE=0
RUN_PYTHON_TESTS=0
LOCAL_RUNTIME_IMAGE="${PITCHCHECK_LOCAL_TRIBE_IMAGE:-pitchcheck-tribe:local}"

usage() {
  cat <<'USAGE'
Usage: npm run install:local -- [options]

Installs or reinstalls PitchCheck from the current repository state.

Options:
  --no-git                Do not fetch/pull the current branch.
  --skip-desktop         Do not build the Tauri desktop installer.
  --skip-package-install Do not install the generated Linux package.
  --skip-runtime-image   Do not pull the configured TRIBE runtime image.
  --local-image NAME     Tag for the locally rebuilt TRIBE image (default: pitchcheck-tribe:local).
  --compose              Rebuild and start docker compose after validation.
  --python-tests         Also create tribe_service/.venv and run pytest.
  -h, --help             Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
  arg="$1"
  case "$arg" in
    --no-git) SKIP_GIT=1 ;;
    --skip-desktop) SKIP_DESKTOP=1 ;;
    --skip-package-install) SKIP_PACKAGE_INSTALL=1 ;;
    --skip-runtime-image) SKIP_RUNTIME_IMAGE=1 ;;
    --local-image)
      if [[ $# -lt 2 ]]; then
        echo "--local-image requires a value." >&2
        exit 2
      fi
      LOCAL_RUNTIME_IMAGE="$2"
      shift
      ;;
    --compose) RUN_COMPOSE=1 ;;
    --python-tests) RUN_PYTHON_TESTS=1 ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

log() {
  printf '\n==> %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

run() {
  log "$*"
  "$@"
}

set_env_value() {
  local file="$1"
  local key="$2"
  local value="$3"
  if [[ -f "$file" ]] && grep -q -E "^${key}=" "$file"; then
    local tmp
    tmp="$(mktemp)"
    awk -v k="$key" -v v="$value" '
      BEGIN { replaced = 0 }
      $0 ~ "^" k "=" && replaced == 0 { print k "=" v; replaced = 1; next }
      $0 ~ "^" k "=" { next }
      { print }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

write_desktop_runtime_config() {
  local image="$1"
  local config_root="${XDG_CONFIG_HOME:-$HOME/.config}"
  local config_dirs=(
    "$config_root/ai.machinity.pitchcheck"
    "$config_root/PitchCheck"
  )
  local openrouter_key
  local openrouter_model
  openrouter_key="$(sed -n 's/^OPENROUTER_API_KEY=//p' .env 2>/dev/null | tail -n 1)"
  openrouter_model="$(sed -n 's/^OPENROUTER_MODEL=//p' .env 2>/dev/null | tail -n 1)"
  openrouter_model="${openrouter_model:-anthropic/claude-sonnet-4.6}"

  for dir in "${config_dirs[@]}"; do
    mkdir -p "$dir"
    umask 077
    cat > "$dir/runtime.env" <<EOF
# PitchCheck machine-local runtime settings
# This file is generated by scripts/install-local.sh and is not part of the repository.
VAST_API_KEY=
OPENROUTER_API_KEY=${openrouter_key}
OPENROUTER_MODEL=${openrouter_model}
PITCHCHECK_TRIBE_IMAGE=${image}
PITCHCHECK_MIN_GPU_RAM_GB=8
PITCHCHECK_MAX_HOURLY_PRICE=0.45
PITCHCHECK_PREFER_INTERRUPTIBLE=true
EOF
    cat > "$dir/service.env" <<EOF
# PitchCheck TRIBE service environment
OPENROUTER_API_KEY=${openrouter_key}
OPENROUTER_MODEL=${openrouter_model}
EOF
  done
}

seed_runtime_cache_volume() {
  local image="$1"
  local volume="pitchcheck_tribe_models"
  run docker volume create "$volume"

  if [[ -d .secrets/huggingface-cache ]]; then
    run docker run --rm \
      -v "${ROOT_DIR}/.secrets/huggingface-cache:/seed/huggingface:ro" \
      -v "${volume}:/models" \
      "$image" \
      sh -c 'mkdir -p /models/huggingface /models/.cache && if [ ! -d /models/huggingface/hub/models--NousResearch--Hermes-3-Llama-3.2-3B ]; then cp -a /seed/huggingface/. /models/huggingface/; fi'
  else
    run docker run --rm \
      -v "${volume}:/models" \
      "$image" \
      sh -c 'mkdir -p /models/huggingface/hub /models/.cache'
  fi
}

require_cmd git
require_cmd node
require_cmd npm
require_cmd cargo
require_cmd rustc

if command -v docker >/dev/null 2>&1; then
  DOCKER_AVAILABLE=1
else
  DOCKER_AVAILABLE=0
fi

if [[ "$SKIP_GIT" -eq 0 ]]; then
  current_branch="$(git rev-parse --abbrev-ref HEAD)"
  run git fetch --prune --tags origin

  if [[ -n "$(git status --porcelain)" ]]; then
    log "Working tree has local changes; leaving branch as-is."
  elif git rev-parse --verify "origin/${current_branch}" >/dev/null 2>&1; then
    run git pull --ff-only origin "$current_branch"
  else
    log "No origin/${current_branch} ref found; leaving branch as-is."
  fi
fi

if [[ ! -f .env && -f .env.example ]]; then
  run cp .env.example .env
fi

if [[ "$SKIP_RUNTIME_IMAGE" -eq 0 && "$DOCKER_AVAILABLE" -eq 1 ]]; then
  base_runtime_image="$(grep -E '^PITCHCHECK_TRIBE_IMAGE=' .env 2>/dev/null | tail -n 1 | cut -d= -f2-)"
  if [[ -z "$base_runtime_image" || "$base_runtime_image" == "$LOCAL_RUNTIME_IMAGE" ]]; then
    base_runtime_image="ghcr.io/aytzey/pitchcheck-tribe:latest"
  fi
  run docker pull "$base_runtime_image"
  run docker build \
    -f tribe_service/Dockerfile.local \
    --build-arg "BASE_IMAGE=$base_runtime_image" \
    -t "$LOCAL_RUNTIME_IMAGE" \
    .
  set_env_value .env PITCHCHECK_TRIBE_IMAGE "$LOCAL_RUNTIME_IMAGE"
  set_env_value .env TRIBE_TEXT_DEVICE auto
  set_env_value .env TRIBE_TEXT_BATCH_SIZE auto
  set_env_value .env TRIBE_TEXT_INPUT_MODE direct
  set_env_value .env TRIBE_SCORE_TIMEOUT_SECONDS 900
  set_env_value .env TRIBE_MAX_SCORE_CONCURRENCY 1
  set_env_value .env TRIBE_OOM_FALLBACK_TEXT_DEVICE accelerate,cpu
  set_env_value .env TRIBE_ACCELERATE_MAX_GPU_MEMORY_GB auto
  set_env_value .env TRIBE_ACCELERATE_MAX_CPU_MEMORY_GB 32
  set_env_value .env TRIBE_ACCELERATE_OFFLOAD_FOLDER /models/offload
  seed_runtime_cache_volume "$LOCAL_RUNTIME_IMAGE"
  write_desktop_runtime_config "$LOCAL_RUNTIME_IMAGE"
fi

run npm ci
run npm run lint
run npm test
run npm run build
run npm run build:desktop-web
run npm run desktop:check

if [[ "$RUN_PYTHON_TESTS" -eq 1 ]]; then
  require_cmd python3
  run python3 -m venv tribe_service/.venv
  # shellcheck disable=SC1091
  source tribe_service/.venv/bin/activate
  run python -m pip install --upgrade pip setuptools wheel
  run python -m pip install -r tribe_service/requirements.txt
  run python -m pytest tribe_service/tests
fi

if [[ "$SKIP_DESKTOP" -eq 0 ]]; then
  run npm run desktop:build

  if [[ "$SKIP_PACKAGE_INSTALL" -eq 0 && "$(uname -s)" == "Linux" ]]; then
    deb_package="$(find src-tauri/target/release/bundle/deb -maxdepth 1 -type f -name '*.deb' -printf '%T@ %p\n' 2>/dev/null | sort -nr | awk 'NR==1 {print $2}')"
    rpm_package="$(find src-tauri/target/release/bundle/rpm -maxdepth 1 -type f -name '*.rpm' -printf '%T@ %p\n' 2>/dev/null | sort -nr | awk 'NR==1 {print $2}')"

    if [[ -n "${deb_package:-}" && -f "$deb_package" && -f /etc/debian_version ]]; then
      if [[ "$EUID" -eq 0 ]]; then
        run apt-get install --reinstall -y "./$deb_package"
      elif sudo -n true 2>/dev/null; then
        run sudo apt-get install --reinstall -y "./$deb_package"
      else
        log "Package built but sudo is not available non-interactively. Install it with:"
        echo "sudo apt-get install -y \"$ROOT_DIR/$deb_package\""
      fi
    elif [[ -n "${rpm_package:-}" && -f "$rpm_package" ]]; then
      if command -v dnf >/dev/null 2>&1; then
        if [[ "$EUID" -eq 0 ]]; then
          run dnf install -y "$rpm_package"
        elif sudo -n true 2>/dev/null; then
          run sudo dnf install -y "$rpm_package"
        else
          log "Package built but sudo is not available non-interactively. Install it with:"
          echo "sudo dnf install -y \"$ROOT_DIR/$rpm_package\""
        fi
      else
        log "RPM package built at $rpm_package, but dnf is not available."
      fi
    else
      log "No Linux package was found after desktop build."
    fi
  fi
fi

if [[ "$RUN_COMPOSE" -eq 1 ]]; then
  if [[ "$DOCKER_AVAILABLE" -ne 1 ]]; then
    echo "Docker is required for --compose." >&2
    exit 1
  fi
  run docker compose up -d --build
fi

log "PitchCheck local install completed."
